version: '3.8'

networks:
  traefik-web:
    external: true

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    restart: unless-stopped
    volumes:
      - ./data:/usr/share/nginx/html/android:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.syncra-cdn-http.entrypoints=http
      - traefik.http.routers.syncra-cdn-http.rule=Host(`cdn.syncra.me`)
      - traefik.docker.network=traefik-web
    networks:
      - traefik-web